version: '3.9'

services:
  db:
    image: postgres:14
    container_name: postgres_containers
    restart: always
    environment:
      POSTGRES_DB: faculdade
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
